# Configurações de intervalos de tempo
time_intervals:
  # Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
  # Valor padrão (em minutos): 10
  send_heroes_for_work:
    init: 10
    end: 15
  
  # Intervalo de tempo para atualizar a posição dos heróis no mapa
  # Valor padrão (em minutos): 3
  refresh_heroes_positions:
    init: 1
    end: 5
  
  # Intervalo de tempo para verificar por novos mapas
  # Valor padrão (em minutos): 3
  check_for_new_map_button:
    init: 1
    end: 5
  
  # Intervalo de tempo para verificar se precisa resolver o capcha.
  # Valor padrão (em minutos): 1
  check_for_capcha: 1

  bcoin_report: 60

  # Intervalo de tempo para verificar se existe solicitação de login
  # Valor padrão (em minutos): 5
  check_for_login:
    init: 3
    end: 8

  # Intervalo de tempo entre movimentos
  # Valor padrão (em segundos): 1
  interval_between_moviments:
    init: 1
    end: 5

# O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
threshold:
  default: 0.7
  commom: 0.8
  select_wallet_buttons: 0.8
  go_to_work_btn: 0.9
  green_bar: 0.9

game:
  game_width: 941
  game_height: 468
  value_chest1: 0.0145
  value_chest2: 0.0325
  value_chest3: 0.1625
  value_chest4: 0.3250

# curl https://api.telegram.org/bot5012946802:AAF39oQO7QB0oOWfdU_9uBzabz49gwqNn1I/getUpdates
telegram:
  telegram_chat_id: ["168801094"]
  telegram_bot_key: "5012946802:AAF39oQO7QB0oOWfdU_9uBzabz49gwqNn1I"
  enable_coin_report: True
  enable_map_report: True

# Valor padrão: 60
scroll_size: 60

# Valor padrão: 3
scroll_attemps: 2

# Valor padrão: true
use_click_and_drag_instead_of_scroll: true

# Valor padrão: 200
click_and_drag_amount: 200

# Valor padrão: green
# Opções disponíveis:
# all   = seleciona todos os heróis (independente da barra de stamina)
# green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
# full  = seleciona somente os heróis com a barra de stamina cheia
select_heroes_mode: "green"

#utilizado para verificar se o envio (verificação da energia) será geral ou conforme o tipo
select_heroes_by_rarity: True

#configuração para envio, conforme a raridade, se a configuração acima estiver = "True"
select_common_heroes_mode: "green"
select_rare_heroes_mode: "green"
select_super_rare_heroes_mode: "full"
select_epic_heroes_mode: "full"
select_legendary_heroes_mode: "full"

# Opção para salvar os logs em arquivo (logs.txt)
# Valor padrão : False
# Opções disponíveis: False ou True
save_log_to_file: False  

usage_multi_account: False
screen_width: 1280
screen_height: 1080

is_macos: True