version: "3"
services:
  bot_bomb:
    container_name: bot_bomb
    tty: true
    build:
      context: .
    restart: unless-stopped
    cap_add:
      # Google Chrome
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3G
    environment:
      - VNC_PASSWORD=123mudar
      - HTTP_PASSWORD=123mudar
      - TZ=America/Sao_Paulo
      - RESOLUTION=1024x800
      - USER=ubuntu
      - PASSWORD=123mudar
    volumes:
       - /dev/shm:/dev/shm
       - ./bomb:/home/ubuntu/Desktop/bomb:rw
    ports:
      - 5900:5900
      - 6080:80