#=========================================================================
#============================ BombCrypto Bot =============================
#=========================================================================

#       oooooooooo.  ooooooooooooo  .oooooo..o   .oooo.     .oooo.
#       `888'   `Y8b 8'   888   `8 d8P'    `Y8 .dP""Y88b  .dP""Y88b
#        888     888      888      Y88bo.            ]8P'       ]8P'
#        888oooo888'      888       `"Y8888o.      .d8P'      .d8P'
#        888    `88b      888           `"Y88b   .dP'       .dP'
#        888    .88P      888      oo     .d8P .oP     .o .oP     .o
#       o888bood8P'      o888o     8""88888P'  8888888888 8888888888

#=========================================================================
#================ Please consider buying me a coffee :) ==================
#=========================================================================
#============== 0x7e665768270dF85A1D398498F9694C17e646Aa8C ===============
#================================= PIX ===================================
#================= 14c6beb5-a38a-46f1-b029-cf2e104712d0 ==================
#=========================================================================

#************************TELEGRAM CONFIG (OPTIONAL)***********************#
#                                                 ..
#                                            ..:::::
#                                       ..::::..::::
#                                 ...::::::. ..::::.
#                            ...:::::::..  .:::::::
#                        .:::::::::::    .::::::::.
#                         ...::::..    :::::::::::
#                                    .::::::::::::
#                                   .:::::::::::::
#                                  ::::::::::::::
#                                  ::.   .:::::-.
#                                  .        .:-:

# [en_US] Start a Telegram conversation with the @btsit_bot and type /id to get your_chat_id.
# [pt_BR] Inicie uma conversa no Telegram com @btsit_bot e digite /id para pegar o your_chat_id.

# [en_US] Start a Telegram conversation with @botfather and type /newbot to get your_telegram_bot_token.
# [pt_BR] Inicie uma conversa no Telegram com @botfather e digite /newbot para pegar o your_telegram_bot_token.

telegram_enable: True
telegram_chat_id: ["231055361","-634132691"]
telegram_bot_token: "5069171002:AAHYkZdkYdZkaOUowfE90latV-a0FZR10Ns"
enable_coin_report: True
enable_map_report: True
format_of_images: "jpg"

# [en_US] Enable to receive call on error/new captcha (in development)
# [pt_BR] Habilitar para receber chamada em caso de erro/novo captcha (em desenvolvimento)
enable_emergency_call: True
